[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='7a32edb05b6fd5f478c94c732d28bec5a89111430c76a98450ee60950c90fbd2'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
